#EX022
nome = input("Qual o seu nome completo?: ")
print("analisando seu nome...")
nome_mai = nome.upper()
nome_min = nome.lower()
nome_letra = len(nome)
nome_1 = nome.find("")
print(f"Seu nome em maiúsculas é {nome_mai}")
print(f"Seu nome em minùsculas é {nome_min}")
print(f"Seu nome tem o comprimento de {nome_letra - nome.count(" ")} letras")
print(f"Seu primeiro nome tem {nome_1} letras")